Devices:
    MixMaster 1:
        pulse-app-slidders:
            brave: 0
            unmapped: 1
            vivaldi-bin: 2
        pulse-master-slidders:
            master: 3
        serialNumber: 10051642
    MixMaster Pro 4:
        pulse-app-slidders:
            brave: 0
        pulse-master-slidders:
            master: 1
        app-media-control:
            brave:
                back: 0
                playpause: 1
                next: 2
            t:
                back: -1
                playpause: -1
                next: -1
        invert_slidders: true
        serialNumber: 10051537
