# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'unmapped' to control all apps that aren't bound to any slider (this ignores master, system, mic and device-targeting sessions)
# important: slider indexes start at 0, regardless of which analog pins you're using!
app-sliders:
  unmapped: 2
  vivaldi-bin: 1
  brave: 0
master-sliders:
  master: 3

button:
  vivaldi-bin: 0

# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# settings for connecting to the arduino board
com_port: /dev/ttyUSB1
baud_rate: 115200
