Devices:
    4 Slider Audio Mixer:
        pulse-app-slidders:
            brave: 0
            unmapped: 1
            vivaldi-bin: 2
        pulse-master-slidders:
            master: 3
        serialNumber: S0S04B00T0001
    Test:
        pulse-app-slidders:
            vivaldi-bin: 0
        app-media-control:
            brave:
                back: -1
                playpause: 0
                next: -1
            vivaldi:
                back: -1
                playpause: 1
                next: -1
        serialNumber: H0S02B03T0001
app:
    theme: ""
    launch_gui_on_start: true
    notifications: true
